version: '3'

services:
  api:
    build: .
    environment:
      SERVER_PORT: 8080
      LOGGING_LEVEL: ${LOGGING_LEVEL}
      MONGO_HOSTNAME: ${MONGO_HOSTNAME}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      RESOURCE_SERVER: ${RESOURCE_SERVER}
      AUTH_SERVER_URI: ${AUTH_SERVER_URI}
      INTROSPECTION_URL: ${INTROSPECTION_URL} 
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
    ports:
      - '8080:8080'
