apiVersion: v1
kind: Service
metadata:
  name: node-fhir-demo
  labels:
    app: node-fhir-demo
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: node-fhir-demo
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-fhir-demo
  labels:
    app: node-fhir-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-fhir-demo
  template:
    metadata:
      labels:
        app: node-fhir-demo
    spec:
      containers:
      - name: node-fhir-demo
        image: jdweeks.azurecr.io/node-fhir-demo:latest
        imagePullPolicy: Always
        env:
        - name: SERVER_PORT
          value: 8080
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /4_0_0/metadata
            port: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: node-fhir-demo
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: fhir.b2fefb07d3254f009c35.eastus2.aksapp.io
    http:
      paths:
      - backend:
          serviceName: node-fhir-demo
          servicePort: 8080
        path: /
